name: Lint ansible yaml

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: --external-sources --exclude=SC2154 
  run-js-linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        yarn install
        yarn lint
        yarn js-check
